# Generated by Django 4.2 on 2025-08-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_programsprojects_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusvideo',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutusvideo',
            name='video_orientation',
            field=models.CharField(choices=[('horizontal', 'Горизонтальное'), ('vertical', 'Вертикальное')], default='horizontal', max_length=10, verbose_name='Ориентация видео'),
        ),
    ]
