# Generated by Django 4.2 on 2025-08-28 14:02

import django.core.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_aboutusvideo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusvideo',
            name='video_orientation',
            field=models.CharField(choices=[('horizontal', 'Горизонтальная'), ('vertical', 'Вертикальная')], default='horizontal', max_length=10, verbose_name='Ориентация видео'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='button_type',
            field=models.CharField(blank=True, choices=[('file', 'Прикрепить файл'), ('link', 'Прикрепить ссылку')], max_length=4, verbose_name='Тип кнопки'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='cover',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
    ]
