# Generated by Django 4.2 on 2025-09-01 14:42

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_aboutusvideo_video_orientation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetedfundraising',
            name='bottom_text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Рекомендованное количество символов - 290', null=True, verbose_name='Нижний текстовый блок'),
        ),
        migrations.AlterField(
            model_name='targetedfundraising',
            name='top_text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Рекомендованное количество символов - 370', null=True, verbose_name='Верхний текстовый блок'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='name',
            field=models.CharField(help_text='максимальное количество символов - 35', max_length=100, verbose_name='Название типа документа'),
        ),
    ]
