# Generated by Django 4.2 on 2025-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_aboutusvideo_video_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_orientation',
            field=models.CharField(blank=True, choices=[('horizontal', 'Горизонтальная'), ('vertical', 'Вертикальная')], default='horizontal', max_length=10, verbose_name='Ориентация видео'),
        ),
        migrations.AddField(
            model_name='news',
            name='video_orientation',
            field=models.CharField(blank=True, choices=[('horizontal', 'Горизонтальная'), ('vertical', 'Вертикальная')], default='horizontal', max_length=10, verbose_name='Ориентация видео'),
        ),
    ]
