# Generated by Django 4.2 on 2025-09-01 16:44

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_article_video_orientation_news_video_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetedfundraising',
            name='bottom_text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Рекомендованное количество символов - 290', null=True, verbose_name='Нижний текстовый блок'),
        ),
        migrations.AlterField(
            model_name='targetedfundraising',
            name='top_text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Рекомендованное количество символов - 370', null=True, verbose_name='Верхний текстовый блок'),
        ),
    ]
