# Generated by Django 4.2 on 2025-09-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_targetedfundraising_bottom_text_block_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterusefullinks',
            options={'ordering': ('title',), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Полезные ссылки'},
        ),
    ]
