# Generated by Django 4.2 on 2025-09-08 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_chapterusefullinks_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainingandinternshipsphoto',
            name='content_tra_order_6ef70d_idx',
        ),
        migrations.RemoveField(
            model_name='trainingandinternshipsphoto',
            name='on_main',
        ),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(help_text='название направления латинскими буквами с тире (URL-слаг)', max_length=100, unique=True, verbose_name='URL-слаг'),
        ),
        migrations.AlterField(
            model_name='trainingandinternships',
            name='date',
            field=models.CharField(max_length=255, verbose_name='Дата или сроки проведения'),
        ),
        migrations.AlterField(
            model_name='trainingandinternships',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='trainingandinternshipsphoto',
            name='image',
            field=models.ImageField(help_text='На главной странице будет фотография, первая в списке.', upload_to='training/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='trainingandinternshipsphoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AddIndex(
            model_name='trainingandinternshipsphoto',
            index=models.Index(fields=['training', 'order'], name='content_tra_trainin_7104be_idx'),
        ),
    ]
