# Generated by Django 4.2 on 2025-09-17 13:26

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_chapterusefullinks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Основной текст'),
        ),
    ]
