# Generated by Django 4.2 on 2025-09-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_remove_trainingandinternshipsphoto_content_tra_order_6ef70d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(help_text='название направления латинскими буквами с тире вместо пробелов (URL-слаг)', max_length=100, unique=True, verbose_name='URL-слаг'),
        ),
        migrations.AlterField(
            model_name='trainingandinternships',
            name='linked_news',
            field=models.URLField(blank=True, help_text='Ссылка вводится только для новости', verbose_name='Ссылка на новость'),
        ),
    ]
