# Generated by Django 4.2 on 2025-09-17 20:03

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_direction_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingandinternships',
            name='action_on_button',
            field=models.CharField(choices=[('detail', 'На подробную страницу'), ('form', 'На форму связи и отклика'), ('url', 'Ссылка на новость')], default='detail', max_length=6, verbose_name='Тип перехода'),
        ),
        migrations.AlterField(
            model_name='trainingandinternships',
            name='add_info',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='trainingandinternships',
            name='linked_news',
            field=models.URLField(blank=True, help_text='Ссылка вводится только для новости', max_length=500, verbose_name='Ссылка на новость'),
        ),
        migrations.AlterField(
            model_name='trainingandinternships',
            name='text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Полное описание'),
        ),
    ]
