# Generated by Django 4.2 on 2025-09-17 20:59

import content.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_alter_trainingandinternships_action_on_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additional_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Дополнительное описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='detailed_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полное описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='redirect_type',
            field=models.CharField(choices=[('detail', 'На подробную страницу'), ('form', 'На форму связи и отклика')], default='detail', max_length=10, verbose_name='Тип перехода'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(validators=[content.validators.validate_not_empty_html], verbose_name='Краткое описание'),
        ),
    ]
