# Generated by Django 4.2 on 2025-09-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_remove_vacancy_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'Документы и отчеты', 'verbose_name_plural': 'Документы и отчеты'},
        ),
    ]
