# Generated by Django 4.2 on 2025-09-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_alter_news_full_text'),
        ('content', '0033_alter_chapter_options'),
    ]

    operations = [
    ]
