# Generated by Django 4.2 on 2025-09-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_merge_20250919_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaching',
            name='place',
        ),
        migrations.AlterField(
            model_name='coaching',
            name='button',
            field=models.CharField(choices=[('aba_therapy', 'на страницу "АВА-терапия"'), ('contacts', 'на контакты'), ('news', 'ссылка на новость')], default='aba_therapy', max_length=11, verbose_name='Тип перехода'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='date',
            field=models.CharField(max_length=255, verbose_name='Дата или сроки проведения'),
        ),
    ]
