# Generated by Django 4.2 on 2025-09-25 16:14

import content.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_merge_20250919_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Рекомендуемое количество символов - 380', validators=[content.validators.validate_not_empty_html], verbose_name='Краткое описание'),
        ),
    ]
