# Generated by Django 4.2 on 2025-10-01 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_alter_vacancy_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaching',
            name='place',
        ),
        migrations.AddField(
            model_name='coaching',
            name='add_info',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дополнительная информация (на фото)'),
        ),
        migrations.AddField(
            model_name='coaching',
            name='photo',
            field=models.ImageField(default='', upload_to='coaching/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coaching',
            name='button',
            field=models.CharField(choices=[('aba_therapy', 'на страницу "АВА-терапия"'), ('contacts', 'на контакты'), ('news', 'ссылка на новость')], default='aba_therapy', max_length=11, verbose_name='Тип перехода'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='course_format',
            field=models.CharField(choices=[('online', 'онлайн'), ('offline', 'офлайн'), ('hybrid', 'гибрид')], max_length=7, verbose_name='Формат курса'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='date',
            field=models.CharField(max_length=255, verbose_name='Дата или сроки проведения'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='service_price',
            field=models.CharField(max_length=255, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='short_text',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.DeleteModel(
            name='CoachingPhoto',
        ),
    ]
