# Generated by Django 4.2 on 2025-09-29 13:33

import content.validators
import django.core.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_remove_coaching_place_alter_coaching_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='photo',
            field=models.ImageField(default='dell', upload_to='coaching/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coaching',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', validators=[content.validators.validate_not_empty_html], verbose_name='дополнительная информация (на фото)'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoachingPhoto',
        ),
    ]
