# Generated by Django 4.2 on 2025-10-02 15:43

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_remove_coaching_place_coaching_add_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlegallery',
            options={'verbose_name': 'Фото статьи Базы знаний', 'verbose_name_plural': 'Галерея фотографий статьи Базы знаний'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_orientation',
        ),
        migrations.AlterField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.chapterknowledgebase', verbose_name='Раздел Базы знаний'),
        ),
        migrations.AlterField(
            model_name='articletextblock',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='текст статьи'),
        ),
        migrations.CreateModel(
            name='ArticleVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('video_orientation', models.CharField(blank=True, choices=[('horizontal', 'Горизонтальная'), ('vertical', 'Вертикальная')], default='horizontal', max_length=10, verbose_name='Ориентация видео')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='content.article', verbose_name='видео')),
            ],
            options={
                'verbose_name': 'Ссылка на видео статьи Базы знаний',
                'verbose_name_plural': 'Ссылки на видео статьи Базы знаний',
            },
        ),
    ]
