# Generated by Django 4.2.25 on 2026-08-11 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_alter_articlegallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingandinternships',
            name='linked_news',
            field=models.CharField(blank=True, help_text='Ссылка вводится только для новости', max_length=500, validators=[django.core.validators.RegexValidator(message='Введите корректный URL или относительный путь (начинается с /)', regex='^(https?://|/).*$')], verbose_name='Ссылка на новость'),
        ),
    ]
