# Generated by Django 4.2.25 on 2026-08-12 21:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0038_alter_trainingandinternships_linked_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('entity_type', models.CharField(choices=[('news', 'Новость'), ('article', 'Статья базы знаний'), ('project', 'Проект'), ('vacancy', 'Вакансия'), ('training', 'Обучение и стажировки'), ('fundraising', 'Адресный сбор'), ('employee', 'Сотрудник'), ('literature', 'Литература'), ('partner', 'Партнёр'), ('review', 'Отзыв'), ('gratitude', 'Благодарность'), ('useful_link', 'Полезная ссылка'), ('report', 'Документы и отчёты'), ('coaching', 'Консультация и обучение'), ('mission', 'Миссия'), ('supervisor', 'Супервизор')], db_index=True, max_length=32, verbose_name='Тип сущности')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, help_text='Текст, очищенный от HTML-разметки.', verbose_name='Текст для поиска')),
                ('external_url', models.CharField(blank=True, help_text='Заполняется, если объект ведёт на внешний ресурс. Значение производное, валидируется на исходной модели.', max_length=500, verbose_name='Внешняя ссылка')),
                ('published_at', models.DateField(blank=True, help_text='Используется для сортировки при равном ранге.', null=True, verbose_name='Дата публикации')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Поисковый вектор')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='contenttypes.contenttype', verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Запись поискового индекса',
                'verbose_name_plural': 'Записи поискового индекса',
                'ordering': ['id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_gin_idx'), models.Index(fields=['entity_type', '-published_at'], name='search_type_published_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='searchentry',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_search_entry_object'),
        ),
    ]
