# Generated by Django 4.2.25 on 2026-08-12 21:13
#
# Вынесено из 0039 отдельной миграцией намеренно.
# CREATE EXTENSION требует прав суперпользователя БД, и на проде
# эта миграция может не примениться. Полнотекстовый поиск работает
# без неё: расширение pg_trgm нужно только для устойчивости
# к опечаткам через TrigramSimilarity.

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_searchentry'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='searchentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='search_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
