# Generated by Django 4.2.25 on 2026-08-13 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_searchentry_trigram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusvideo',
            name='url',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='Введите корректный URL или относительный путь (начинается с /)', regex='^(https?://|/).*$')], verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='link_button',
            field=models.CharField(blank=True, help_text='Ссылка вводится только для новости', max_length=500, validators=[django.core.validators.RegexValidator(message='Введите корректный URL или относительный путь (начинается с /)', regex='^(https?://|/).*$')], verbose_name='Ссылка на новость'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='interviews',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='Введите корректный URL или относительный путь (начинается с /)', regex='^(https?://|/).*$')], verbose_name='Интервью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='detail_page_link',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator(message='Введите корректный URL или относительный путь (начинается с /)', regex='^(https?://|/).*$')], verbose_name='Ссылка на подробную страницу'),
        ),
    ]
